---
title: Hendricks Family Cookbook
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: _recipes
    type: recipes
  values:
    layout: post
email: ljh.softwaredev@gmail.com
description: Hendricks family recipes.
baseurl: "/"
url: https://hendricksfamilycookbook.com
github_username: liamhendricks
theme: jekyll-theme-basically-basic
gems:
- jekyll-paginate-v2
exclude:
- Gemfile.lock
pagination:
  debug: true
  collection: recipes
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  title: " - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
