---
title: Hendricks Family Cookbook
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    read_time: true
- scope:
    path: _recipes
    type: recipes
  values:
    layout: post
    read_time: true
email: ljh.softwaredev@gmail.com
description: Hendricks family recipes.
baseurl: "/"
url: https://hendricksfamilycookbook.com
github_username: liamhendricks
theme: jekyll-theme-basically-basic
paginate: 5
paginate_path: "/page:num/"
exclude:
- Gemfile.lock
